# Generated by Django 6.0.6 on 2026-07-04 03:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0002_currency_country_code_currency_decimal_places"),
        ("rates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("buy_rate", models.DecimalField(decimal_places=2, max_digits=15)),
                ("sell_rate", models.DecimalField(decimal_places=2, max_digits=15)),
                ("source", models.CharField(default="mock_api", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="currencies.currency",
                    ),
                ),
            ],
        ),
    ]
