# Generated by Django 6.0.6 on 2026-07-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="country_code",
            field=models.CharField(
                default="NG", help_text="ISO Country Code (US, GB, NG...)", max_length=2
            ),
        ),
        migrations.AddField(
            model_name="currency",
            name="decimal_places",
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
